POOII_T1_DIEGOENRIQUEZ/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace POOII_T1_DIEGOENRIQUEZ.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

POOII_T1_DIEGOENRIQUEZ/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace POOII_T1_DIEGOENRIQUEZ.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

POOII_T1_DIEGOENRIQUEZ/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace POOII_T1_DIEGOENRIQUEZ.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

POOII_T1_DIEGOENRIQUEZ/Pages/Productos/Crear.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using POOII_T1_DIEGOENRIQUEZ.Datos;
using POOII_T1_DIEGOENRIQUEZ.Modelos;
//inyeccion de datos//
namespace POOII_T1_DIEGOENRIQUEZ.Pages.Productos
{
    public class CrearModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public CrearModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Personal Personal { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

      

            _context.Add(Personal);
            await _context.SaveChangesAsync();

            return RedirectToPage("Index");
        }
    }
}

POOII_T1_DIEGOENRIQUEZ/Pages/Productos/Editar.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using POOII_T1_DIEGOENRIQUEZ.Datos;
using POOII_T1_DIEGOENRIQUEZ.Modelos;

//inyeccion de datos//
namespace POOII_T1_DIEGOENRIQUEZ.Pages.Productos
{
    public class EditarModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditarModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Personal Personal { get; set; }
        public async Task OnGet(int id)
        {
            Personal = await _context.Personal.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)

            {
                var PersonalDB = await _context.Personal.FindAsync(Personal.Id);
                PersonalDB.Nombre = Personal.Nombre;
                PersonalDB.Apellido = Personal.Apellido;
                PersonalDB.FechaIngreso = Personal.FechaIngreso;
                PersonalDB.Area = Personal.Area;
                PersonalDB.Sueldo = Personal.Sueldo;
                PersonalDB.Seniority = Personal.Seniority;

                await _context.SaveChangesAsync();

                return RedirectToPage("Index");
            }

            return RedirectToPage();
        }
    }
}

POOII_T1_DIEGOENRIQUEZ/Pages/Productos/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using POOII_T1_DIEGOENRIQUEZ.Datos;
using POOII_T1_DIEGOENRIQUEZ.Modelos;
//inyeccion de datos//
namespace POOII_T1_DIEGOENRIQUEZ.Pages.Productos
{
    public class IndexModel : PageModel
    {
        public readonly ApplicationDbContext _context;

        public IndexModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IEnumerable<Personal> Personal { get; set; }

        public async Task OnGet()
        {
            Personal = await _context.Personal.ToListAsync();
        }

        public async Task<IActionResult> OnPostBorrar(int id)
        {
            var producto = await _context.Personal.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }

            _context.Personal.Remove(producto);
            await _context.SaveChangesAsync();
            //Redigiremos a la pagina index//
            return RedirectToPage("Index");
        }
    }
}

POOII_T1_DIEGOENRIQUEZ/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

POOII_T1_DIEGOENRIQUEZ/Pages/Productos/Crear.cshtml
@page
@model POOII_T1_DIEGOENRIQUEZ.Pages.Productos.CrearModel
@{
    ViewData["Title"] = "Crear nuevo personal";
}
<div class="card">
    <div class="card-header bg-dark">
        <div class="row">
            <div class="col-sm-9">
                <h2 class="text-info">Crear Nuevo Personal</h2>
            </div>
        </div>
    </div>

    <div class="card-body">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="container" style="padding: 30px">
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Personal.Nombre"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Personal.Nombre" class="form-control" />
                        </div>
                        <span asp-validation-for="Personal.Nombre" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Personal.Apellido"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Personal.Apellido" class="form-control" />
                        </div>
                    <span asp-validation-for="Personal.Apellido" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                        <label asp-for="Personal.FechaIngreso"></label>
                        </div>
                        <div class="col-sm-6">
                        <input asp-for="Personal.FechaIngreso" class="form-control" />
                        </div>
                    <span asp-validation-for="Personal.FechaIngreso" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                        <label asp-for="Personal.Area"></label>
                        </div>
                        <div class="col-sm-6">
                        <input asp-for="Personal.Area" class="form-control" />
                        </div>
                    <span asp-validation-for="Personal.Area" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Personal.Sueldo"></label>
                        </div>
                        <div class="col-sm-6">
                        <input asp-for="Personal.Sueldo" class="form-control" />
                        </div>
                    <span asp-validation-for="Personal.Sueldo" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Personal.Seniority"></label>
                        </div>
                        <div class="col-sm-6">
                        <input asp-for="Personal.Seniority" class="form-control" />
                        </div>
                    <span asp-validation-for="Personal.Seniority" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group mt-4">
                    <div class="row">
                        <div class="col-sm-2 offset-sm-2">
                            <input type="submit" value="Crear" class="btn btn-primary form-control" />
                        </div>
                        <div class="col-sm-4">
                            <a asp-page="Index" class="btn btn-success form-control">Volver a la lista del personal</a>
                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>

POOII_T1_DIEGOENRIQUEZ/Pages/Productos/Editar.cshtml
@page
@model POOII_T1_DIEGOENRIQUEZ.Pages.Productos.EditarModel
@{
    ViewData["Title"] = "Editar Personal";
}
<div class="card">
    <div class="card-header bg-dark">
        <div class="row">
            <div class="col-sm-9">
                <h2 class="text-info">Editar Personal</h2>
            </div>
        </div>
    </div>

    <div class="card-body">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Personal.Id" />

            <div class="container" style="padding: 30px">
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Personal.Nombre"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Personal.Nombre" class="form-control" />
                        </div>
                        <span asp-validation-for="Personal.Nombre" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Personal.Apellido"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Personal.Apellido" class="form-control" />
                        </div>
                        <span asp-validation-for="Personal.Apellido" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Personal.FechaIngreso"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Personal.FechaIngreso" class="form-control" />
                        </div>
                        <span asp-validation-for="Personal.FechaIngreso" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Personal.Area"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Personal.Area" class="form-control" />
                        </div>
                        <span asp-validation-for="Personal.Area" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Personal.Sueldo"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Personal.Sueldo" class="form-control" />
                        </div>
                        <span asp-validation-for="Personal.Sueldo" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Personal.Seniority"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Personal.Seniority" class="form-control" />
                        </div>
                        <span asp-validation-for="Personal.Seniority" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group mt-4">
                    <div class="row">
                        <div class="col-sm-2 offset-sm-2">
                            <input type="submit" value="Editar" class="btn btn-primary form-control" />
                        </div>
                        <div class="col-sm-4">
                            <a asp-page="Index" class="btn btn-success form-control">Volver a la lista de personal</a>
                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>

POOII_T1_DIEGOENRIQUEZ/Pages/Productos/Index.cshtml
@page
@model POOII_T1_DIEGOENRIQUEZ.Pages.Productos.IndexModel
@{
    ViewData["Title"] = "Lista de Personal";
}
<div class="card">
    <div class="card-header bg-dark">
        <div class="row">
            <div class="col-sm-9">
                <h2 class="text-info">Lista de personal</h2>
            </div>
            <div class="col-sm-3">
                <a asp-page="Crear" class="btn btn-primary">Crear Nuevo Personal</a>
            </div>
        </div>
    </div>

    <div class="card-body">
        <form method="post">
            @if (Model.Personal.Count() > 0)
            {
                <br />
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>@Html.DisplayNameFor(m => m.Personal.First().Id)</th>
                        <th>@Html.DisplayNameFor(m => m.Personal.First().Nombre)</th>
                        <th>@Html.DisplayNameFor(m => m.Personal.First().Apellido)</th>
                        <th>@Html.DisplayNameFor(m => m.Personal.First().FechaIngreso)</th>
                        <th>@Html.DisplayNameFor(m => m.Personal.First().Area)</th>
                        <th>@Html.DisplayNameFor(m => m.Personal.First().Sueldo)</th>
                        <th>@Html.DisplayNameFor(m => m.Personal.First().Seniority)</th>
                        <th>Acciones</th>
                    </tr>
                    @foreach (var item in Model.Personal)
                    {
                        <tr>
                            <td>@Html.DisplayFor(m => item.Id)</td>
                            <td>@Html.DisplayFor(m => item.Nombre)</td>
                            <td>@Html.DisplayFor(m => item.Apellido)</td>
                            <td>@Html.DisplayFor(m => item.FechaIngreso)</td>
                            <td>@Html.DisplayFor(m => item.Area)</td>
                            <td>@Html.DisplayFor(m => item.Sueldo)</td>
                            <td>@Html.DisplayFor(m => item.Seniority)</td>
                            <td>
                                <a asp-route-id="@item.Id" asp-page="Editar" class="btn btn-success btn-sm">Editar</a>
                                <button asp-page-handler="Borrar" asp-route-id="@item.Id" onclick="return confirm('Estas seguro que quieres borrar?')" class="btn btn-danger btn-sm">Borrar</button>
                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>No hay ningun personal</p>
            }
        </form>
    </div>
</div>

POOII_T1_DIEGOENRIQUEZ/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - POOII_T1_DIEGOENRIQUEZ</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/POOII_T1_DIEGOENRIQUEZ.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">POOII_T1_DIEGOENRIQUEZ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Productos/Index">Administracion de Empleados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - POOII_T1_DIEGOENRIQUEZ - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>